[package]
name = "bevy-test-server"
version = "0.1.0"
edition = "2021"
authors = ["akosnad"]

[dependencies]
bevy_app = "0.15.1"
bevy_ecs = "0.15.1"
bevy_stardust = "0.7.2"
env_logger = "0.11.6"
log = "0.4.25"
